#!/bin/bash

dirname=$(dirname ${0})

. ${dirname}/common-functions

args=${1}

if [ -n "${2}" ]; then
	args=${2}
fi

provides=$(find_provides ${args})
requires=""
for require in $(find_requires ${args}); do
	listmatch ${require} ${provides} || requires="${requires} ${require}"
done

echo "provides=\"${provides}\""
echo "requires=\"${requires}\""

exit 0
