#!/bin/bash

dirname=$(dirname ${0})

. ${dirname}/common-functions

action=${1}
shift

case "${action}" in
	requires)
		find_requires $@
		exit $?
		;;

	provides)
		find_provides $@
		exit $?
		;;
esac

exit 1
