#!/bin/bash

for patch in $@; do
	echo "Applying file ${patch}..."

	if [ "${patch##*/*.}" = "patch0" ]; then
		cmd="patch -Np0"
	else
		cmd="patch -Np1"
	fi

	${cmd} -i ${patch}
	ret=$?

	if [ ${ret} -ne 0 ]; then
		exit ${ret}
	fi
done
