#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2015  Michael Tremer                                          #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

ALGOS="rsa ecdsa ed25519"

main() {
	local ret=0

	local algo
	for algo in ${ALGOS}; do
		local keyfile="/etc/ssh/ssh_host_${algo}_key"

		# If the key already exists, there is nothing to do
		[ -e "${keyfile}" ] && continue

		# Generate a new key
		if ! ssh-keygen -qf "${keyfile}" -N '' -t "${algo}"; then
			ret=1
			continue
		fi

		# Fix permissions
		chgrp ssh_keys "${keyfile}"
		chmod 600 "${keyfile}"
		chmod 644 "${keyfile}.pub"
	done

	return ${ret}
}

main; exit $?
